version: "3"
services:
  chrome:
    image: selenium/standalone-chrome:4.0.0-20211025
    shm_size: 2gb
    container_name: chrome
    volumes:
      - ./tmp/dev/shm:/dev/shm
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
